"""add_asset_quality_and_feedback

Revision ID: 575351136703
Revises: 57aaaca5967c
Create Date: 2026-04-06 17:03:35.636534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575351136703'
down_revision = '57aaaca5967c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_feedback',
    sa.Column('asset_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('session_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('issue_tags', sa.JSON(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_feedback_asset_id_assets')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_asset_feedback_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_feedback'))
    )
    op.create_index(op.f('ix_asset_feedback_asset_id'), 'asset_feedback', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_feedback_session_id'), 'asset_feedback', ['session_id'], unique=False)
    op.create_index(op.f('ix_asset_feedback_user_id'), 'asset_feedback', ['user_id'], unique=False)
    op.add_column('assets', sa.Column('quality_status', sa.String(length=32), nullable=False, server_default='unchecked'))
    op.add_column('assets', sa.Column('quality_scores', sa.JSON(), nullable=True))
    op.add_column('assets', sa.Column('quality_review_job_id', sa.Uuid(as_uuid=False), nullable=True))
    op.add_column('assets', sa.Column('failure_reason', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_assets_quality_review_job_id'), 'assets', ['quality_review_job_id'], unique=False)
    op.create_index(op.f('ix_assets_quality_status'), 'assets', ['quality_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_quality_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_quality_review_job_id'), table_name='assets')
    op.drop_column('assets', 'failure_reason')
    op.drop_column('assets', 'quality_review_job_id')
    op.drop_column('assets', 'quality_scores')
    op.drop_column('assets', 'quality_status')
    op.drop_index(op.f('ix_asset_feedback_user_id'), table_name='asset_feedback')
    op.drop_index(op.f('ix_asset_feedback_session_id'), table_name='asset_feedback')
    op.drop_index(op.f('ix_asset_feedback_asset_id'), table_name='asset_feedback')
    op.drop_table('asset_feedback')
    # ### end Alembic commands ###
